### ISSUE TITLE
Uncaught TypeError: Cannot read property 'append' of undefined

### ISSUE THREAD

**Issue by anaibol** [ezhilvendhan/import#12]
Hi, thanks for this usefull plugin!!!
I am having an issue on windows, when opening files.

TypeError: Cannot read property 'append' of undefined
  at C:\Users\amicheli\.atom\packages\import\lib\import-view.coffee:69:29
  at ChildProcess.exithandler (child_process.js:199:7)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:172:7)
  at maybeClose (internal/child_process.js:764:16)
  at Socket.<anonymous> (internal/child_process.js:319:11)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:169:7)
  at Pipe._onclose (net.js:467:12)

**Comment by ezhilvendhan** [comment]
Hi @anaibol 
Thanks for logging this. Please pull the latest package and let me know if you still face this.

Thanks
Ezhil

**Comment by anaibol** [comment]
Seems to be working since then :)

**Comment by ezhilvendhan** [comment]
Awesome!

**Comment by anaibol** [comment]
Hi, the issue if coming back!

````
/C:/Users/amicheli/.atom/packages/import/lib/import-view.coffee:131
Hide Stack Trace
TypeError: atom.views.getView(...).append is not a function
  at C:\Users\amicheli\.atom\packages\import\lib\import-view.coffee:69:46
  at ChildProcess.exithandler (child_process.js:199:7)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:172:7)
  at maybeClose (internal/child_process.js:764:16)
  at Socket.<anonymous> (internal/child_process.js:319:11)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:169:7)
  at Pipe._onclose (net.js:467:12)
