### ISSUE TITLE
Uncaught TypeError: atom.views.getView(...).append is not a function

### ISSUE THREAD

**Issue by anaibol** [ezhilvendhan/import#13]
Hi!
This issue has reappeared. Am I the only one?

**Atom Version**: 1.1.0
**System**: Unknown Windows Version
**Thrown From**: [import](https://github.com/ezhilvendhan/import) package, v1.6.0

### Stack Trace

Uncaught TypeError: atom.views.getView(...).append is not a function

```
At /C:/Users/amicheli/.atom/packages/import/lib/import-view.coffee:131

TypeError: atom.views.getView(...).append is not a function
  at C:\Users\amicheli\.atom\packages\import\lib\import-view.coffee:69:46
  at ChildProcess.exithandler (child_process.js:199:7)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:172:7)
  at maybeClose (internal/child_process.js:764:16)
  at Socket.<anonymous> (internal/child_process.js:319:11)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:169:7)
  at Pipe._onclose (net.js:467:12)

```

### Commands

```
  2x -1:57.7.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -1:56.2.0 core:save (atom-text-editor.editor.is-focused)
     -1:43.6.0 core:undo (atom-text-editor.editor.is-focused.autocomplete-active)
  3x -1:42.1.0 core:save (atom-text-editor.editor.is-focused)
     -0:48.4.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -0:46.8.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:46.8.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:21.1.0 core:copy (atom-text-editor.editor.is-focused.hyperclick)
     -0:20.8.0 find-and-replace:show (atom-text-editor.editor.is-focused.hyperclick)
     -0:20.7.0 core:paste (atom-text-editor.editor.mini.is-focused)
  5x -0:20.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:19.5.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:19.5.0 core:cancel (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-c",
      "language-clojure",
      "language-coffee-script",
      "language-csharp",
      "language-gfm",
      "language-go",
      "code-links"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-import-sort, v0.5.0
autocomplete-modules, v1.3.1
autocomplete-paths, v1.0.2
hyperclick, v0.0.32
import, v1.6.0
js-hyperclick, v1.4.0
language-babel, vundefined
minimap, v4.16.0
node-debugger, v1.1.9
react, v0.12.10
riot, v0.2.5
visual-bell, v1.0.0

# Dev
No dev packages
```

**Comment by ezhilvendhan** [comment]
Hi @anaibol 
The Windows VM I use does not have this issue. However I managed to add a fix. I suppose the issue happens in a specific scenario which I could not replicate. Feel free to reopen the issue if you face it. :)

Thanks
Ezhil

**Comment by anaibol** [comment]
Ok!
