### ISSUE TITLE
Failed to load the import package

### ISSUE THREAD

**Issue by sabeurthabti** [ezhilvendhan/import#9]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.190.0
**System**: Mac OS X 10.9.5
**Thrown From**: [import](https://github.com/ezhilvendhan/import) package, v1.1.0

### Stack Trace

Failed to load the import package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (/Users/s.thabti/.atom/packages/import/lib/import-view.coffee:4:199)
    at /Users/s.thabti/.atom/packages/import/lib/import-view.coffee:15:5
    at Object.<anonymous> (/Users/s.thabti/.atom/packages/import/lib/import-view.coffee:194:5)
    at Object.<anonymous> (/Users/s.thabti/.atom/packages/import/lib/import-view.coffee:196:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "projectHome": "~/workspace",
    "excludeVcsIgnoredPaths": false,
    "followSymlinks": true,
    "showIndentGuide": true,
    "useShadowDOM": true,
    "zoomFontWhenCtrlScrolling": true,
    "themes": [
      "one-dark-ui",
      "one-dark-syntax"
    ],
    "disabledPackages": [
      "hide-files",
      "term2"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.6.0
formatter, v2.12.2
import, v1.1.0
language-ejs, v0.1.0
language-gradle, v0.0.3
linter-jsonlint, v0.1.2
linter-scss-lint, v0.0.14
markdown-pdf, v1.3.5
minimap, v4.6.0
npm-autocomplete, v0.1.2
open-terminal-here, v0.5.0
pretty-json, v0.3.2
react, v0.9.11

# Dev
No dev packages
```

**Comment by ezhilvendhan** [comment]
Could not replicate this on OS X 10.10.3, Atom 0.191.0.
Do you still face this issue? Can you try updating the import version?

**Comment by sabeurthabti** [comment]
I just removed the package.
